service: covid19-data-crawler
app: covid19-data
org: lcrss

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  data:
    handler: crawler.handler
    events:
      - http:
          path: data
          method: get
          cors: true
